// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CollaborationGraphController from "./collaboration_graph_controller"
application.register("collaboration-graph", CollaborationGraphController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ThemeMapperController from "./theme_mapper_controller"
application.register("theme-mapper", ThemeMapperController)
