services:

  web:
    volumes:
      - .:/rails
    ports:
      - "3000:3000"

  sidekiq:
    command: bundle exec sidekiq
    environment:
      - LOG_LEVEL=debug
      
  nginx:
    ports:
      - "8085:80"

  redis:
    entrypoint: ["echo", "Service redis disabled"]
